// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEw092W-c5LrzGMLW9BDjzEHIK8hxZC4s',
    appId: '1:238726799721:web:f9abe83318d25b1b859df8',
    messagingSenderId: '238726799721',
    projectId: 'trandaycat',
    authDomain: 'trandaycat.firebaseapp.com',
    storageBucket: 'trandaycat.firebasestorage.app',
    measurementId: 'G-B06SFKCWBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBry8gstsi_6s0L8czD6v8DG06VCeLzCgg',
    appId: '1:238726799721:android:5b80f4e9e58c48f7859df8',
    messagingSenderId: '238726799721',
    projectId: 'trandaycat',
    storageBucket: 'trandaycat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMnuOsQdD5W9CJDtDOZeHAcjdqrhPvtY',
    appId: '1:238726799721:ios:fb0ef5c89b049c0b859df8',
    messagingSenderId: '238726799721',
    projectId: 'trandaycat',
    storageBucket: 'trandaycat.firebasestorage.app',
    iosBundleId: 'com.example.trendycart',
  );

}